package bankofthailand

var BankCode = map[string]string{
	"BOTH":  "001",
	"BBL":   "002",
	"KBANK": "004",
	"KTB":   "006",
	"TTB":   "011",
	"SCB":   "014",
	"BAY":   "025",
	"KKP":   "069",
	"CIMBT": "022",
	"TISCO": "067",
	"UOBT":  "024",
	"TCD":   "071",
	"LHFG":  "073",
	"ICBCT": "070",
	"SME":   "098",
	"BAAC":  "034",
	"EXIM":  "035",
	"GSB":   "030",
	"GHB":   "033",
	"ISBT":  "066",
}

var SwiftCode = map[string]string{
	"BOTH":  "BOTHTHBK",
	"BBL":   "BKKBTHBK",
	"KBANK": "KASITHBK",
	"KTB":   "KRTHTHBK",
	"TTB":   "TMBKTHBK",
	"SCB":   "SICOTHBK",
	"BAY":   "AYUDTHBK",
	"KKP":   "KIFITHB1",
	"CIMBT": "UBOBTHBK",
	"TISCO": "TFPCTHB1",
	"UOBT":  "UOVBTHBK",
	"TCD":   "THCETHB1",
	"LHFG":  "LAHRTHB1",
	"ICBCT": "ICBKTHBK",
	"SME":   "",
	"BAAC":  "BAABTHBK",
	"EXIM":  "EXTHTHBK",
	"GSB":   "GSBATHBK",
	"GHB":   "",
	"ISBT":  "TIBTTHBK",
}
